"use client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { adminService } from "@/services/adminService";
import { AdminForm, AdminNav, AdminPage, Field } from "@/components/admin/AdminTools";
export default function AdminSubscriptionsPage() {
  const client = useQueryClient();
  const subscriptions = useQuery({ queryKey: ["admin", "subscriptions"], queryFn: () => adminService.subscriptions({ page: 0, size: 50 }) });
  const deactivate = useMutation({ mutationFn: adminService.deactivateExpiredSubscriptions, onSuccess: () => client.invalidateQueries({ queryKey: ["admin", "subscriptions"] }) });
  return <AdminPage title="Suscripciones y planes" description="Administrá planes y mantené actualizado el estado de membresías."><AdminNav /><button onClick={() => deactivate.mutate()} className="rounded-lg border border-border px-4 py-2 text-sm">Desactivar vencidas</button><AdminForm onSubmit={(v) => adminService.createSubscriptionPlan({ ...v, durationDays: Number(v.durationDays), price: Number(v.price), maxBooksAllowed: Number(v.maxBooksAllowed), maxDaysPerBook: Number(v.maxDaysPerBook), displayOrder: Number(v.displayOrder) })}><div className="grid gap-3 sm:grid-cols-2"><Field name="planCode" label="Código" required /><Field name="name" label="Nombre" required /><Field name="description" label="Descripción" /><Field name="durationDays" label="Duración (días)" type="number" /><Field name="price" label="Precio" type="number" /><Field name="maxBooksAllowed" label="Máximo de libros" type="number" /><Field name="maxDaysPerBook" label="Días por libro" type="number" /><Field name="displayOrder" label="Orden" type="number" /></div></AdminForm><section className="rounded-2xl border border-border/70 bg-card">{subscriptions.isLoading ? <p className="p-5 text-sm text-muted-foreground">Cargando...</p> : subscriptions.data?.content.map((subscription) => <div key={subscription.id} className="flex justify-between border-b border-border/60 px-5 py-4 text-sm last:border-0"><span>{subscription.planName}</span><span className="text-muted-foreground">{subscription.planCode} · {subscription.active ? "Activa" : "Inactiva"}</span></div>)}</section></AdminPage>;
}
